# This workflow will build a golang project for multiple platforms and update releases
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            suffix: linux-amd64
          - os: linux
            arch: 386
            suffix: linux-386
          - os: linux
            arch: arm
            suffix: linux-arm
          - os: linux
            arch: arm64
            suffix: linux-arm64
          - os: windows
            arch: amd64
            suffix: windows-amd64.exe
          - os: windows
            arch: 386
            suffix: windows-386.exe
          - os: windows
            arch: arm
            suffix: windows-arm.exe
          - os: windows
            arch: arm64
            suffix: windows-arm64.exe
          - os: darwin
            arch: amd64
            suffix: darwin-amd64
          - os: darwin
            arch: arm64
            suffix: darwin-arm64

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      env:
        GOOS: ${{ matrix.os }}
        GOARCH: ${{ matrix.arch }}
      run: go build -v -o progwrp-patcher-${{ matrix.suffix }} ./...

    - name: Get latest release
      id: get_latest_release
      run: |
        # Check if there's a latest release
        LATEST_RELEASE=$(gh api repos/${{ github.repository }}/releases/latest --jq '.tag_name' 2>/dev/null || echo "")
        
        if [ -z "$LATEST_RELEASE" ]; then
          echo "No release found, creating one..."
          # Create a release with the current commit hash as tag
          COMMIT_HASH=$(git rev-parse --short HEAD)
          gh release create "v0.0.0-$COMMIT_HASH" --title "Development Release $COMMIT_HASH" --notes "Auto-generated release for commit $COMMIT_HASH"
          LATEST_RELEASE="v0.0.0-$COMMIT_HASH"
        fi
        
        echo "release_tag=$LATEST_RELEASE" >> $GITHUB_OUTPUT
        echo "Using release: $LATEST_RELEASE"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete existing assets
      run: |
        LATEST_TAG="${{ steps.get_latest_release.outputs.release_tag }}"
        
        # Get all assets for the latest release
        ASSETS=$(gh api repos/${{ github.repository }}/releases/latest --jq '.[] | select(.name | contains("progwrp-patcher") and (.name | endswith(".zip") | not)) | .id' 2>/dev/null || echo "")
        
        # Delete each existing asset
        if [ -n "$ASSETS" ]; then
          for asset_id in $ASSETS; do
            echo "Deleting asset ID: $asset_id"
            gh api repos/${{ github.repository }}/releases/assets/$asset_id -X DELETE
          done
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      run: |
        LATEST_TAG="${{ steps.get_latest_release.outputs.release_tag }}"
        echo "Uploading to release: $LATEST_TAG"
        
        # Upload the binary with clobber to replace existing one
        gh release upload "$LATEST_TAG" progwrp-patcher-${{ matrix.suffix }} --clobber
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}